### ISSUE TITLE
Integrate highdicom w/ DICOM web viewer

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/highdicom#144]
Dear Sir,

The highdicom provides powerful DICOM SR and annotations API. But it seems to require integration with DICOM viewer.

As far as we know, Slim viewer doesn't include highdicom python package, correct? But it can generate corresponding annotations and SRs. Would you mind if I ask why Slim is not developed in python and then uses the highdicom package?

If we use the highdicom kit to develop the digital pathology web viewer and generate annotations and SRs at the same time, could you give some suggestions?

Thanks.

**Comment by hackermd** [comment]
highdicom and Slim have been designed to serve two different purposes:

- *highdicom* is a library to encode/decode machine-generated image annotations and analysis results in DICOM format. Since most researchers and developers use Python to develop image analysis and machine learning solutions, *highdicom* has been implemented in the Python programming language.
- *Slim* is a single-page web application that runs in the browser. Therefore, it has been implemented in JavaScript/TypeScript.

Note that the *Slim* viewer supports encoding of annotations using DICOM Structured Reporting (SR).

**Comment by DrexlerChao** [comment]
Hi @hackermd 

Thank you very much for your detailed and clear explanation.
