### ISSUE TITLE
SC Images are not included in the list of _iods.py 

### ISSUE THREAD

**Issue by codezizo** [MGHComputationalPathology/highdicom#32]
This issue is because the generic Secondary Captures UID is no longer in the DICOM spec. However, they are still wildly used and thus should be supported.

**Comment by hackermd** [comment]
I just double-checked the current edition of the standard (2020b) to confirm that it still specifies the [Secondary Capture (SC) Image IOD](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.8.html).

I think the problem was that the naming convention used for keys of the `IOD_MODULE_MAP` did not match the [storage class name assigned by pydicom](https://github.com/pydicom/pydicom/blob/master/pydicom/_storage_sopclass_uids.py#L167). Therefore, the lookup operation failed:

https://github.com/MGHComputationalPathology/highdicom/blob/dba9cbb34e6da9fa019e0c5a7ec43496e4f7ce89/src/highdicom/base.py#L240

This should be fixed by 6fd6e8ef67439cd7fa0f67724210bce10d79175b, which changed the key in `IOD_MODULE_MAP` from `"sc-image"` to `"secondary-capture-image"`:
https://github.com/MGHComputationalPathology/highdicom/commit/6fd6e8ef67439cd7fa0f67724210bce10d79175b#diff-877f252df373b0092509d0f42b36e1b1R10363

@codezizo Could you please try again with 6fd6e8ef67439cd7fa0f67724210bce10d79175b and let me know whether it works now?

**Comment by codezizo** [comment]
@hackermd just tested this morning and it worked! 

Thanks for fixing! Glad it was an easier fix than what we had thought previously. 

Cheers!

**Comment by hackermd** [comment]
I am going to add a few unit tests and draft a new release including these changes within the next week or so.
