### ISSUE TITLE
It is possible to create qualitative evaluations with no relationship types

### ISSUE THREAD

**Issue by CPBridge** [MGHComputationalPathology/highdicom#61]
I created an SR which contained qualitative evaluations, which are passed in as a sequence of `CodeContentItems` to the `qualitative_evaluations` parameter of the various SRs. I constructed these `CodeContentItems` without the `relationship_type` parameter, and highdicom did not issue any warnings or complaints. However the dciodvfy tool raises an error saying that the `RelationshipType` is required and therefore the SR objects are invalid.

I am not sure exactly what the right level to solve this issue is.

The simplest way is simply to check the elements of `qualitative_evaluations` when constructing `MeasurementsAndQualitativeEvaluations` objects to ensure they have `RelationshipType`s. However after thinking about this more I think that this specific issue may be a symptom of a broader problem. Currently the `relationship_type` is an optional parameter for a `ContentItem` and all its subclasses (e.g. `CodeContentItem`, `TimeContentItem`,`NumContentItem`, ...). I'm not sure that this is correct. I think it should probably be required.

My reading of table [C.17-6](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.html#table_C.17-6) is that RelationshipType is a type 1 (required) attribute within a `ContentSequence`. I tried making `relationship_type` a required parameter of `ContentItem` and all subclasses, and the only tests that failed were tests where these objects were directly constructed without the relationship type parameter by test code. I.e. there is no place in the main codebase where an item is constructed without a relationship type (or at least not one with test coverage I suppose...). I haven't been able to think of a situation where a relationship type wouldn't be needed. The one place I'm unsure about is the very root of the content tree, which doesn't have a relationship to its parent. I'm not sure how to understand the recursive standard docs on this point. But even there it seems like highdicom is currently placing a `RelationshipType` attribute at the root of the tree anyway

Another option is that maybe the append method of `ContentSequence` should have a check to ensure that the `ContentItem` being appended has a `RelationshipType`. 

@hackermd can you help please me understand at what level this issue exists?

**Comment by hackermd** [comment]
Hmm... That's a tricky one!

> Currently the relationship_type is an optional parameter for a ContentItem and all its subclasses (e.g. CodeContentItem, TimeContentItem,NumContentItem, ...). I'm not sure that this is correct. I think it should probably be required.

I think the parameter should definitely be optional for the base class, since there are content items that don't have a parent/target item or don't require a relationship type to be specified. I am not sure either what would be correct for the derived classes. Looking through the templates in Part16, I found several content items of value type `CONTAINER` or `NUM` that don't require a relationship type. I also found ones of value type `CODE` that do not seem to require a relationship type (e.g., [TID 1200 Row 1](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#para_7eb0d9cb-457c-43e6-b6b5-10fe68c2d33b)). That's why I decided to make the parameter optional for all classes and handle the specification of relationships in the implementation of a `Template` class. However, I didn't realize that this would become a problem in cases where content items are passed by the caller, as you discovered with `qualitative_evaluations`.

I would suggest asserting the correct relationship type for a given row in the template class (or even set/overwrite the value as specified by the template?). In hindsight, it may have been better to not set the attribute on instances of `ContentItem`, but add them in the context of a template, such that a `ContentItem` instance itself only represents the content without the need to know the document context (i.e., the template row).

@dclunie @fedorov do you have any further insight or suggestion on how to best implement this?

**Comment by CPBridge** [comment]
I think your approach of not setting it as an attribute of `ContentItem` seems right. Maybe it should be a second parameter to the `ContentSequence.append()` method? If so, we could gradually phase this in, initially overwriting any RelationshipType already present in the `ContentItem` and retiring the parameter to `ContentItem` with a deprecation warning until 1.0 and then removing entirely?

For this specific problem, another solution might be creating a specific subclass of `CodeContentItem` for `QualitativeEvaluation`, which automatically sets up the `RelationshipType` correctly and then retiring `CodeContentItem` as a valid parameter type for the SR templates (again gradually through deprecation warnings).

**Comment by hackermd** [comment]
> I think your approach of not setting it as an attribute of `ContentItem` seems right.

I have previously modeled a `ContentItem` to represent a row in a SR template and decided to add the `RelationshipType` attribute upon construction of the item (resulting in high cohesion). However, there are clear advantages to adding the attribute only when adding an item to a `ContentSequence`, where the relationship is actually established (see [C.17.3.2.4 Content Sequence and Relationship Type](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.2.4.html)).

In addition, the attribute is specified as part of a separate macro, i.e., in [Document Relationship Macro Attributes](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.html#table_C.17-6) rather than in [Document Content Macro Attributes](dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.html#table_C.17).

> Maybe it should be a second parameter to the `ContentSequence.append()` method? If so, we could gradually phase this in, initially overwriting any RelationshipType already present in the ContentItem and retiring the parameter to ContentItem with a deprecation warning until 1.0 and then removing entirely?

That sounds like a good approach. If we do that now, we should probably also change all occurrences in `highdicom.sr.templates` and `highdicom.sr.content` (and potentially at other locations where the `relationship_type` parameter may be used) to facilitate subsequent deprecation and to not provide developers bad examples for copy-paste.

For example:

```python
        name_item = TextContentItem(
            name=CodedConcept(
                value='111001',
                meaning='Algorithm Name',
                scheme_designator='DCM'
            ),
            value=name,
            relationship_type=RelationshipTypeValues.HAS_CONCEPT_MOD
        )
        self.append(name_item)
```
to
```python
        name_item = TextContentItem(
            name=CodedConcept(
                value='111001',
                meaning='Algorithm Name',
                scheme_designator='DCM'
            ),
            value=name
        )
        self.append(name_item, relationship_type=RelationshipTypeValues.HAS_CONCEPT_MOD)
```

> For this specific problem, another solution might be creating a specific subclass of `CodeContentItem` for `QualitativeEvaluation`, which automatically sets up the `RelationshipType` correctly and then retiring `CodeContentItem` as a valid parameter type for the SR templates (again gradually through deprecation warnings).

I am not sure whether this would work for all (current and future) templates that may use a "qualitative evaluation", which is a vaguely defined concept. I would prefer your suggestion to transition to specifying the Relationship Type when adding a content item to the `ContentSequence` where the relationship is established.

**Comment by fedorov** [comment]
> Looking through the templates in Part16, I found several content items of value type CONTAINER or NUM that don't require a relationship type. I also found ones of value type CODE that do not seem to require a relationship type (e.g., TID 1200 Row 1). That's why I decided to make the parameter optional for all classes and handle the specification of relationships in the implementation of a Template class.

I did not find where TID 1200 is used, but [TID 300](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_300) has similar issue. I do not think this implies that the relationship type is not required. What I believe this means is that the relationship is defined in the parent template invoking the current template. As an example, TID 300 is invoked from [TID 1501](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#table_TID_1501) row 10, and in that invocation the relationship for Row 1 of TID 300 will be CONTAINS.

**Comment by fedorov** [comment]
> However the dciodvfy tool raises an error 

You should also consider running the SR validator from Pixelmed Toolkit - `DicomSRValidator.sh` in http://www.dclunie.com/pixelmed/software/index.html, which will validate content at the level of TIDs. `dciodvfy` does not do that.

**Comment by hackermd** [comment]
> I think I still don't understand this SR structure as well as you both do but that from my current understanding that seems like the right approach. As a general point, since we are pre-1.0 and have a small userbase I don't think we should be too scared of making backwards incompatible changes that are well thought-through and handled appropriately (deprecation warnings etc). Better that than be stuck with a sub-optimal design decision forever more

Alright. Let's do it via the phase approach you proposed:

- Keep `relationship_type` as an optional parameter of `ContentItem.__init__()` (and derived classes) and add deprecation warning that this parameter will be removed in a future version.
- Add `relationship_type`as a parameter to `ContentSequence.append()`, making it optional for now and issue a warning that the attribute will be required in a future version if omitted.
- Update package to consistently use `ContentSequence.append(..., relationship_type=...)`.

@CPBridge did I get this right?

**Comment by dclunie** [comment]
I dont have suggestions about the API as long as when serialized a value for Relationship Type is always supplied, so that invalid objects are not be created ... see http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.2.4.html <http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.17.3.2.4.html> 

I.e., at some point it needs to be required, not optional.

On April 1, 2021 11:44:22 AM EDT, "Markus D. Herrmann" ***@***.***> wrote:


I think I still don't understand this SR structure as well as you both do but that from my current understanding that seems like the right approach. As a general point, since we are pre-1.0 and have a small userbase I don't think we should be too scared of making backwards incompatible changes that are well thought-through and handled appropriately (deprecation warnings etc). Better that than be stuck with a sub-optimal design decision forever more

Alright. Let's do it via the phase approach you proposed:

*	Keep relationship_type as an optional parameter of ContentItem.__init__() (and derived classes) and add deprecation warning that this parameter will be removed in a future version.
*	Add relationship_typeas a parameter to ContentSequence.append(), making it optional for now and issue a warning that the attribute will be required in a future version if omitted.
*	Update package to consistently use ContentSequence.append(..., relationship_type=...).

@CPBridge did I get this right?

**Comment by hackermd** [comment]
@dclunie thanks for clarification!

**Comment by CPBridge** [comment]
Revisiting this stale thread in the hope of resolving soon...

Several weeks ago I spent a while working on implementing the solution proposed above, before getting disillusioned with it and then getting distracted by shinier things. You can see my aborted progress on the `refactor_content_sequence_relationships` branch if you are curious.

I now believe that the solution proposed above (moving responsibility for establishing relationships from the time of construction of content items to the the point at which the content item is appended to a template), while it sounds like a nice idea in principle, is in fact impractical given the design of the rest of the library. I started down this path by adding a required `relationship_type` parameter to the `append()` and `extend()` methods of the `ContentSequence` class. This lead to a couple of problematic observations:

1. Template classes derived from the `ContentSequence` python class are often added to other content sequences/templates by `.extend()`ing them, i.e. adding all items in the sequence/template to the other sequence at once. In order the establish the relationship type at this point would require passing the relationship types for the content items in the sequence to the `.extend()` method, which requires either passing a single relationship type and assuming it applied to all items in the sequence (which is too limiting for some templates) or passing a list of relationship types with one for each content item (which breaks the encapsulation of the template classes in a serious way and leads to a very ugly and confusing interface).

2. Content items may be added to sequences multiple times, leading to redundant establishment of relationships. This mostly occurs because constructors of templates perform `self.append()` and `self.extend()` operations, and then another `append`/`extend` operation is used when the template is added to the parent. Arguably it makes no sense to establish the relationship type within the constructor as avoiding this was the original purpose of this entire exercise. However, if `relationship_type` is a required parameter of `append`/`extent`, there is no way to avoid this. On the other hand If `relationship_type` were not a required parameter of `append`/`extend`, there is no way to guarantee that a relationship type is ever established.

For an example of both these problems, consider the `ReferencedSegment` class, with simplified constructor (I have added comments where the relationship types would need to be specified under the proposal):

```python
class ReferencedSegment(ContentSequence):
    def __init__(
        ...
        source_images: Optional[
            Sequence[SourceImageForSegmentation]
        ] = None,
        source_series: Optional[SourceSeriesForSegmentation] = None
    ) -> None:
        super().__init__()
        segment_item = ImageContentItem(
            ...
            relationship_type=RelationshipTypeValues.CONTAINS
        )
        self.append(segment_item)  # CONTAINS
        if source_images is not None:
            for image in source_images:
                ...
                self.append(image)  # INFERRED_FROM
        elif source_series is not None:
            ...
            self.append(source_series) # INFERRED_FROM)
```

which is then used in the `_ROIMeasurementsAndQualitativeEvaluations` constructor, simplified below:

```python
class _ROIMeasurementsAndQualitativeEvaluations(
        MeasurementsAndQualitativeEvaluations):

    def __init__(
        self,
        ...
        referenced_segment: Optional[
            Union[ReferencedSegment, ReferencedSegmentationFrame]
        ] = None,
        ...
    ):
        super().__init__(
        ...
        elif referenced_segment is not None:
            group_item.ContentSequence.extend(referenced_segment)  # what relationship type here?
```

Notice: 
1. The `ReferencedSegments` sequence contains content items with different relationship types to the parent (CONTAINS and INFERRED_FROM), that under the proposal would need to be established in the `self.append()` methods (marked) in the `ReferencedSegment` constructor.
2. The relationship types would need to be re-established in the constructor of `_ROIMeasurementsAndQualitativeEvaluations`, when the entire `ReferencedSegment` content sequence is `.extend()`ed onto the `_ROIMeasurementsAndQualitativeEvaluations` sequence. This would require somehow specifying the three relationship types again, redundantly.

Given this example, you might be tempted to think that the solution is to require a relationship type to be established during a call to `.append()` and not `.extend()`. I don't totally rule this out but I think it is not the right solution because it does not seem self-consistent, and gives rise to awkward issues elsewhere.

I therefore believe that we should drop the approach proposed above and focus more narrowly on solving the original issue by:
1. Deprecating construction of `ContentItem`s with no relationship type, as I believe the consensus reached above is that this is never valid. I have come to the conclusion that establishing the relationship type once here is the only sensible way to guarantee that one is established. Furthermore, after seeing several examples, it has become clear that the `relationship_type` is unambiguous at the time of construction of the content item in all the examples I have seen so far.
2. Checking that qualitative evaluations have the correct relationship type (which I believe should be `CONTAINS`) after they are passed to the `MeasurementsAndQualitativeEvaluations` constructor and overwriting it with a warning if it is incorrect. Unfortunately this requires the user to manually specify the relationship type, which feels rather low-level. Another alternative is creating a CodeContentItem subclass specifically for `QualitativeEvaluation` which correctly establishes the relationship type automatically upon construction. I personally lean towards the latter approach, but note that a qualitative evaluation is not a well defined DICOM concept.

Thoughts @hackermd, all?

**Comment by hackermd** [comment]
I like the idea of introducing `highdicom.sr.content.QualitativeEvaluation`. To me, a "qualitative evaluation" is a content item of value type CODE that represents a categorical feature when compared to a "measurement", which is a content item of value type NUM that represents a discrete or continuous feature.

**Comment by hackermd** [comment]
@CPBridge and I just realized that content items may not specify a relationship type because according to DICOM [PS 3.16 6.1.3 Relationship With Source Content Item](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_6.html#sect_6.1.3)

> Acquisition Context and Protocol Context Templates have no Relationship field
