### ISSUE TITLE
Should PixelOriginInterpetation be required?

### ISSUE THREAD

**Issue by fedorov** [MGHComputationalPathology/highdicom#79]
PixelOriginInterpetation is only required for Whole slide microscopy, see https://dicom.innolitics.com/ciods/extensible-sr/sr-document-content/00480301, but highdicom essentially makes it Type 1.

The problem with this is when defining region of interest for non-WSI images. It is not clear what is the meaning of VOLUME PixelInterpretationOrigin for CT, for example, since Total Pixel Matrix Origin seems to be WSI-specific. At the same time, it is impossible to define PixelInterpretationOrigin to be FRAME, since there is no frame number for non-enhanced images.

Most logical to me would be to allow passing None as `pixel_origin_interpretation` parameter value to the `ImageRegion` constructor, but instead of assigning VOLUME when None is passed (see https://github.com/MGHComputationalPathology/highdicom/blob/master/src/highdicom/sr/content.py#L481) not including this attribute in the dataset.

At the moment, I can only initialize that attribute to VOLUME.

**Comment by hackermd** [comment]
Thanks for reporting this issue @fedorov. I am not sure whether including the attribute independent of the SOP class should be considered wrong, since the standard says that it "may be present otherwise". However, the default value should probably be FRAME rather than VOLUME, which would be semantically equivalent to the attribute not being present.

I would also be fine with not including the attribute at all if `pixel_origin_interpretation` is `None` and `source_image.ReferencedSOPClassUID` is not `"1.2.840.10008.5.1.4.1.1.77.1.6"` and agree that this would probably be the cleanest approach.

**Comment by hackermd** [comment]
This will also require modifying `ScoordContentItem`. The fact that Pixel Origin Interpretation is a 1C attribute is unfortunate. To me, it's generally a bad idea to have a condition in module/macro that depends on context outside of its scope, since it significantly complicates implementation.

**Comment by hackermd** [comment]
@fedorov should be fixed with 81e3cb7b7e51d6c6c3b07fbf43ca9eb96bee1b94

**Comment by fedorov** [comment]
Thank you Markus for addressing this so quickly! You fixed this before I could even look into how to propose a fix myself.
